"""Generate guide/concepts/sector-reference.mdx from data/sectors.csv.

Run from the repo root after updating the CSV:
    python3 scripts/build-sector-reference.py
"""

import csv
import re
from collections import defaultdict
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
SOURCE = ROOT / "data" / "sectors.csv"
TARGET = ROOT / "guide" / "concepts" / "sector-reference.mdx"

# Internal placeholder codes that shouldn't appear in the docs
SKIP_CODES = {"43320*"}


def escape(text):
    """Escape characters that MDX or Markdown tables would interpret."""
    for char, replacement in (("\\", "\\\\"), ("|", "\\|"), ("<", "&lt;"), (">", "&gt;"),
                              ("{", "\\{"), ("}", "\\}"), ("*", "\\*"), ("_", "\\_")):
        text = text.replace(char, replacement)
    return text


def code_sort_key(code):
    # NACE codes first in numeric order, then virtual codes
    return (0, code) if re.fullmatch(r"\d{5}", code) else (1, code)


def main():
    sectors = defaultdict(lambda: defaultdict(list))
    with SOURCE.open(encoding="utf-8-sig") as f:
        for row in csv.DictReader(f):
            if row["code"] in SKIP_CODES:
                continue
            sectors[row["name"]][row["name_en"]].append((row["code"], row["description_nl"].strip()))

    lines = [
        "---",
        'title: "Sector reference"',
        'description: "All aiGust sectors and subsectors, with the NACE codes and virtual codes that belong to each."',
        "---",
        "",
        "{/* Generated by scripts/build-sector-reference.py from data/sectors.csv. Don't edit by hand. */}",
        "",
        "This page lists every sector and subsector in aiGust, with the codes that belong to each. "
        "Use it to check where an administration's NACE code falls, or which codes a sector covers when you define a peer group. "
        "For how sectors work, see [Sectors and company types](/guide/concepts/sectors-and-company-types).",
        "",
        "Besides NACE codes, the list contains aiGust's virtual codes:",
        "",
        "- **RIZIV codes,** such as `RIZIV-10-S07`, for medical specialisations.",
        "- **Carpentry codes** `43320_in` and `43320_ex`, which split NACE code 43320 into interior and exterior carpentry.",
        "",
        "Descriptions follow the Dutch NACE nomenclature. To find a code quickly, use your browser's search (Cmd+F or Ctrl+F) after opening a sector.",
        "",
        "<AccordionGroup>",
    ]

    for sector in sorted(sectors, key=str.lower):
        subsectors = sectors[sector]
        count = sum(len(codes) for codes in subsectors.values())
        lines += ["", f'<Accordion title="{sector}" description="{len(subsectors)} subsectors, {count} codes">', ""]
        for subsector in sorted(subsectors, key=str.lower):
            lines += [f"**{escape(subsector)}**", "", "| Code | Description |", "|---|---|"]
            for code, description in sorted(subsectors[subsector], key=lambda c: code_sort_key(c[0])):
                lines.append(f"| `{code}` | {escape(description)} |")
            lines.append("")
        lines.append("</Accordion>")

    lines += ["", "</AccordionGroup>", ""]
    TARGET.write_text("\n".join(lines), encoding="utf-8")
    print(f"Wrote {TARGET.relative_to(ROOT)}: {len(sectors)} sectors")


if __name__ == "__main__":
    main()
