"""Generate setup/data/social/social-balance-codes.mdx from data/social_balance_codes.csv.

Run from the repo root after updating the CSV:
    python3 scripts/build-social-balance-codes.py
"""

import csv
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
SOURCE = ROOT / "data" / "social_balance_codes.csv"
TARGET = ROOT / "setup" / "data" / "social" / "social-balance-codes.mdx"

# English names of the categories (Hoofdcategorie) in the CSV
CATEGORIES = {
    "Aantal werknemers": "Number of employees",
    "Gepresteerde Uren": "Hours worked",
    "Kosten": "Costs",
    "Uitzendkrachten": "Temporary workers",
    "Opleidingen": "Training",
}

# How the value of a code is calculated over a period (the type column in the CSV)
TYPES = {
    "period_avg": "Average",
    "period_total": "Total",
    "end": "End",
}


def escape(text):
    """Escape characters that MDX or Markdown tables would interpret."""
    for char, replacement in (("\\", "\\\\"), ("|", "\\|"), ("<", "&lt;"), (">", "&gt;"),
                              ("{", "\\{"), ("}", "\\}"), ("*", "\\*"), ("_", "\\_")):
        text = text.replace(char, replacement)
    return text


def main():
    categories = {}
    with SOURCE.open(encoding="utf-8-sig") as f:
        for row in csv.DictReader(f, skipinitialspace=True):
            row = {key.strip(): value.strip() for key, value in row.items()}
            categories.setdefault(row["Hoofdcategorie"], []).append(row)

    total = sum(len(rows) for rows in categories.values())
    lines = [
        "---",
        'title: "Social balance codes"',
        'description: "All codes of the social balance sheet that aiGust imports, with the name of the KPI each one becomes in aiGust."',
        "---",
        "",
        "{/* Generated by scripts/build-social-balance-codes.py from data/social_balance_codes.csv. Don't edit by hand. */}",
        "",
        f"This page lists the {total} codes of the social balance sheet that aiGust imports, "
        "with the name of the KPI each one becomes in aiGust. It's for reference only: you don't need it to set up a social connector. "
        "For where the social balance sheet comes from, see [Social data overview](/setup/data/social/overview).",
        "",
        "Not every social balance sheet has all codes. aiGust looks for each of them, and imports the ones it finds.",
        "",
        "The codes are those of the National Bank of Belgium. The descriptions are in Dutch, as on the social balance sheet. "
        "**Value** says how aiGust calculates a code over a period:",
        "",
        "- **Average:** the average over the period, such as the average number of employees.",
        "- **Total:** the total over the period, such as the hours worked.",
        "- **End:** the value at the end of the period, such as the number of employees on the last day.",
        "",
        "To find a code quickly, open a category and use your browser's search (Cmd+F or Ctrl+F).",
        "",
        "<AccordionGroup>",
    ]

    for category, rows in categories.items():
        title = f"{CATEGORIES.get(category, category)} ({category})"
        lines += ["", f'<Accordion title="{title}" description="{len(rows)} codes">', "",
                  "| Code | Description | KPI name | Value |", "|---|---|---|---|"]
        for row in rows:
            lines.append(f"| `{row['NBB Code']}` | {escape(row['Dutch'])} | `{row['KPI Name']}` | "
                         f"{TYPES.get(row['type'], row['type'])} |")
        lines += ["", "</Accordion>"]

    lines += ["", "</AccordionGroup>", ""]
    TARGET.write_text("\n".join(lines), encoding="utf-8")
    print(f"Wrote {TARGET.relative_to(ROOT)}: {total} codes in {len(categories)} categories")


if __name__ == "__main__":
    main()
